- name: "Update package repo"
  apt:
    update_cache: yes

- name: "Setup KlipperScreen packages"
  apt:
    name:
      - xserver-xorg-video-fbturbo
      - xdotool
      - xinit
      - xinput
      - x11-xserver-utils
      - libopenjp2-7
      - python3-distutils
      - python3-gi
      - python3-gi-cairo
      - python3-virtualenv
      - gir1.2-gtk-3.0
      - virtualenv
      - matchbox-keyboard
      - wireless-tools
      - libatlas-base-dev
      - fonts-freefont-ttf
      - xserver-xorg-video-fbdev
    state: present

- name: Clone KlipperScreen repo
  git:
    repo: "{{ klipperscreen_git_url }}"
    dest: "{{ klipperscreen_src_dir }}"
    accept_hostkey: yes
  become_user: "{{ klipper_user }}"

- name: "Create python virtual env for KlipperScreen"
  shell: virtualenv -p /usr/bin/python3 {{ klipperscreen_env_dir }}
  become_user: "{{ klipper_user }}"

- name: "Update pip for KlipperScreen"
  shell: |
    {{ klipperscreen_env_dir }}/bin/pip install -U pip
  become_user: "{{ klipper_user }}"

- name: "Install pip vext vext.gi for KlipperScreen"
  shell: |
    {{ klipperscreen_env_dir }}/bin/pip install --no-use-wheel vext vext.gi
  become_user: "{{ klipper_user }}"
  ignore_errors: yes

- name: "Install pip requirements for KlipperScreen"
  shell: |
    {{ klipperscreen_env_dir }}/bin/pip install -r {{ klipperscreen_src_dir }}/scripts/KlipperScreen-requirements.txt
  become_user: "{{ klipper_user }}"
  ignore_errors: yes

- name: "Apply vext -e to the klipperscreen environemnt"
  shell: "{{ klipperscreen_env_dir }}/bin/vext -e"
  become_user: "{{ klipper_user }}"
  ignore_errors: yes

- name: Install systemd service
  template:
    src: files/klipperscreen/KlipperScreen.service.j2
    dest: /etc/systemd/system/KlipperScreen.service
    owner: root
    group: root

- name: Overwrite Xwrapper.config
  template:
    src: files/klipperscreen/Xwrapper.config.j2
    dest: /etc/X11/Xwrapper.config
    owner: root
    group: root

- name: Start KlipperScreen service
  systemd:
    name: KlipperScreen
    daemon_reexec: yes
    state: restarted
    enabled: yes
