---
# vars file for klipper-stack
klipper_user: "klipper"
klipper_user_home: "/home/{{ klipper_user }}"
klipper_logs_dir: "{{ klipper_user_home }}/klipper_logs"
klipper_src_dir: "{{ klipper_user_home }}/klipper"
klipper_config_dir: "{{ klipper_user_home }}/klipper_config"
klipper_env_dir: "{{ klipper_user_home }}/klipper-env"

klipperscreen_git_url: "https://github.com/jordanruthe/KlipperScreen.git"
klipperscreen_src_dir: "{{ klipper_user_home }}/klipperscreen"
klipperscreen_env_dir: "{{ klipper_user_home }}/klipperscreen-env"

moonraker_log_path: "/tmp/moonraker.log"
moonraker_src_dir: "{{ klipper_user_home }}/moonraker"
moonraker_env_dir: "{{ klipper_user_home }}/moonraker-env"
moonraker_config_path: "{{ klipper_config_dir }}/moonraker.conf"
moonraker_launch_cmd: "{{ moonraker_env_dir }}/bin/python {{ moonraker_src_dir }}/moonraker/moonraker.py"
moonraker_server_ip: "{{ ansible_ssh_host }}"
moonraker_server: "{{ moonraker_server_ip }}:7125"
moonraker_git_url: "https://github.com/Arksine/moonraker.git"

nginx_sites_available_path: "/etc/nginx/sites-available"
nginx_sites_enabled_path: "/etc/nginx/sites-enabled"

fluidd_assets_path: "/var/www/fluidd"
fluidd_version: "1.16.2"

webcam_server_ip: "{{ ansible_ssh_host }}"
webcam_server: "{{ moonraker_server_ip }}:8080"
mjpg_streamer_git_url: "https://github.com/jacksonliam/mjpg-streamer"
mjpg_streamer_src_path: "{{ klipper_user_home }}/mjpg-streamer"
mjpg_streamer_compiled_path: "{{ mjpg_streamer_src_path }}/mjpg-streamer-experimental"
mjpg_streamer_width: 1080
mjpg_streamer_height: 720
mjpg_streamer_fps: 60
mjpg_streamer_rot: 0
